---
- name: Base setup for all nodes
  hosts: all
  become: true
  roles:
    - common

- name: Configure web server
  hosts: web
  become: true
  roles:
    - web

- name: Configure database server
  hosts: db
  become: true
  roles:
    - db
