---
- name: Install PostgreSQL server and tools
  apt:
    name: "{{ postgresql_packages }}"
    state: present
    update_cache: true
  notify: restart postgresql

- name: Ensure PostgreSQL is enabled and running
  service:
    name: postgresql
    state: started
    enabled: true

- name: Ensure database user exists
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: "LOGIN"

- name: Ensure database exists
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"

- name: Allow local md5 connections (demo)
  lineinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    regexp: '^host\s+all\s+all\s+127\.0\.0\.1/32\s+'
    line: 'host    all             all             127.0.0.1/32            md5'
    insertafter: '^#? IPv4 local connections:'
  notify: reload postgresql
